---
title: "DS4420_Final_Project"
author: "Jack Roberge, Christian Peterson, Shreesh Dassarkar"
date: "2025-12-01"
output: html_document
---

```{r preprocessing}

# imports
library(caret)
library(dplyr)
library(fastDummies) 
library(ggplot2)
library(tidyr)

set.seed(40)

# read in data
nfl_data <- read.csv(
  "/Users/jroberge/Downloads/nfl_2019.csv", 
  stringsAsFactors = FALSE, 
  na.strings = c("NA", "", "NULL", "-")
)

# keep only plays that are clearly passes or runs
missing_indices <- which(is.na(nfl_data$pass_length) & is.na(nfl_data$run_location))
nfl_data <- nfl_data[-missing_indices, ]

# create specific play column (target variable)
nfl_data$play_call <- NA_character_

# short left pass
nfl_data$play_call[
  nfl_data$pass_length == "short" & nfl_data$pass_location == "left"
] <- "short left pass"

# short right pass
nfl_data$play_call[
  nfl_data$pass_length == "short" & nfl_data$pass_location == "right"
] <- "short right pass"

# deep left pass
nfl_data$play_call[
  nfl_data$pass_length == "deep" & nfl_data$pass_location == "left"
] <- "deep left pass"

# deep right pass
nfl_data$play_call[
  nfl_data$pass_length == "deep" & nfl_data$pass_location == "right"
] <- "deep right pass"

# left run
nfl_data$play_call[
  nfl_data$run_location == "left"
] <- "left run"

# right run
nfl_data$play_call[
  nfl_data$run_location == "right"
] <- "right run"

# drop all other plays 
nfl_data <- nfl_data[!is.na(nfl_data$play_call), ]

# make column a factor 
nfl_data$play_call <- factor(
  nfl_data$play_call,
  levels = c(
    "short left pass",
    "short right pass",
    "deep left pass",
    "deep right pass",
    "left run",
    "right run"
  )
)

y_target <- nfl_data$play_call
x_features <- c("posteam", "side_of_field", "shotgun", "no_huddle",
                "yrdln", "down", "goal_to_go", "qtr",
                "game_seconds_remaining", "posteam_score")
x_data <- nfl_data[x_features]

x_data$side_of_field <- ifelse(
  x_data$posteam == x_data$side_of_field,
  "Theirs",
  "Opposing"
)

# one hot encode categorical columns
categ_cols <- c("posteam", "side_of_field", "yrdln", "down")
x_data <- dummy_cols(x_data, select_columns = categ_cols, 
                     remove_first_dummy = FALSE)
x_data <- x_data[, !(names(x_data) %in% categ_cols)] 

# normalize continuous features
continuous_cols <- c("game_seconds_remaining", "posteam_score")
x_data[, continuous_cols] <- scale(x_data[, continuous_cols])

# bias term
x_data$bias <- 1
X_all <- as.matrix(x_data)
storage.mode(X_all) <- "numeric"

# split into training, test data
trainIndex <- createDataPartition(y_target, p = .75, list = FALSE, times = 1)
X_train <- X_all[trainIndex,]
X_test <- X_all[-trainIndex,]

Y_all <- model.matrix(~ play_call - 1, data = nfl_data)

Y_train <- Y_all[trainIndex, ]
Y_test  <- Y_all[-trainIndex, ]

Y_train <- as.matrix(Y_train)
storage.mode(Y_train) <- "numeric"
Y_test <- as.matrix(Y_test)
storage.mode(Y_test) <- "numeric"

```


```{r mlp setup}

# initial attempt (pre hyperparameter-tuning)

set.seed(40) # maintain state

eta <- 0.1 # step size
q <- 24 # hidden nodes

n <- nrow(X_train) # number of samples
d <- ncol(X_train) # number of features + 1 (bias term)
k <- ncol(Y_train) # number of classes

W1 <- matrix(rnorm(d * q), nrow = d, ncol = q) # initial W1
W2 <- matrix(rnorm(q * k), nrow = q, ncol = k) # initial W2

# leaky relu
leaky_relu <- function(x, alpha = 0.01) {
  ifelse(x > 0, x, alpha * x)
}

# softmax
softmax <- function(x) {
  x_shift <- x - apply(x, 1, max) # infinity values were causing errors
  exp_x <- exp(x_shift)
  exp_x / rowSums(exp_x)
}

# forward pass func
forward_pass <- function(X, W1, W2) {
  Hidden_input <- X %*% W1              
  Hidden_output <- leaky_relu(Hidden_input)
  Output_input <- Hidden_output %*% W2          
  Y_pred <- softmax(Output_input)       
  
  list(Y_pred = Y_pred, Hidden_output = Hidden_output, 
       Hidden_input = Hidden_input)
}
```

```{r mlp}

errors <- numeric() # to track errors over epochs
epochs <- 500 # number of epochs

# backprop
for (epoch in 1:epochs) {
  # forward pass
  fwd <- forward_pass(X_train, W1, W2)
  
  # gradients
  dW2 <- t(fwd$Hidden_output) %*% (fwd$Y_pred - Y_train) / n
  dW1 <- t(X_train) %*% (((fwd$Y_pred - Y_train) %*% t(W2)) * 
                           ifelse(fwd$Hidden_input > 0, 1, 0.01)  ) / n
  
  # weight updates
  W2 <- W2 - eta * dW2
  W1 <- W1 - eta * dW1
  
  # calculate and track loss
  epsilon <- 1e-15 # to avoid log(0) error 
  L <- -mean(rowSums(Y_train * log(fwd$Y_pred + epsilon)))
  errors <- c(errors, L)
}

# output results
cat("Loss at epoch 0:", round(errors[1], 4), "\n")
cat("Loss at epoch 500:", round(errors[length(errors)], 4), "\n")

```


``` {r evaluate initial mlp}

# predictions
fwd_test <- forward_pass(X_test, W1, W2)
predicted <- apply(fwd_test$Y_pred, 1, which.max)
true <- apply(Y_test, 1, which.max)

# calculate accuracy
accuracy <- mean(predicted == true)
cat("Our test data accuracy is", round(accuracy, 4), "\n")

# calculate comparative accuracy metrics
# random guessing
cat("Random guessing yields an accuracy of", round((1/6), 4), "\n")

# most common play guess
play_counts <- table(true)
guess_most_common_play <- max(play_counts) / length(true)

play_names <- levels(nfl_data$play_call)
most_common_play_idx <- as.numeric(names(which.max(play_counts)))
most_common_play <- play_names[most_common_play_idx]
cat("Simply guessing the most common play", most_common_play, "yields an 
    accuracy of", round(guess_most_common_play, 4), "\n")


# confusion matrix
confusion_matrix <- table(Predicted = predicted, Actual = true)

# create confusion heatmap
confusion_df <- as.data.frame(confusion_matrix)
names(confusion_df) <- c("Predicted", "Actual", "Count")

confusion_df$predicted_play <- factor(play_names[as.numeric(confusion_df$Predicted)])
confusion_df$actual_play <- factor(play_names[as.numeric(confusion_df$Actual)])

confusion_heatmap <- ggplot(confusion_df, aes(x = actual_play, y = predicted_play, 
                                           fill = Count)) +
  geom_tile(color = "black") +
  geom_text(aes(label = Count), color = "black", size = 4) +
  scale_fill_gradient(low = "white", high = "steelblue") +
  labs(title = "Confusion Matrix", x = "Actual Play", 
       y = "Predicted Play") +
  theme_minimal() +
  scale_x_discrete(limits = play_names) +
  scale_y_discrete(limits = rev(play_names))

print(confusion_heatmap)


# create directionally independent confusion matrix (no left/right)

play_groups <- c("Short Pass", "Deep Pass", "Run")
play_groups_map <- c("Short Pass", "Short Pass", "Deep Pass", "Deep Pass", 
                     "Run", "Run")

predicted_play_group <- factor(play_groups_map[predicted], levels = play_groups)
true_play_group <- factor(play_groups_map[true], levels = play_groups)

confusion_matrix_play_group <- table(Predicted = predicted_play_group, 
                                 Actual = true_play_group)
confusion_matrix_df_play_group <- as.data.frame(confusion_matrix_play_group)
names(confusion_matrix_df_play_group) <- c("Predicted", "Actual", "Count")

confusion_matrix_df_play_group$predicted_play <- factor(
  play_groups[as.numeric(confusion_matrix_df_play_group$Predicted)])
confusion_matrix_df_play_group$actual_play <- factor(
  play_groups[as.numeric(confusion_matrix_df_play_group$Actual)])

confusion_heatmap_play_group <- ggplot(confusion_matrix_df_play_group, 
                                       aes(x = actual_play, 
                                           y = predicted_play, 
                                           fill = Count)) +
  geom_tile(color = "black") +
  geom_text(aes(label = Count), color = "black", size = 4) +
  scale_fill_gradient(low = "white", high = "steelblue") +
  labs(title = "Play Group Confusion Matrix", x = "Actual Play Group", 
       y = "Predicted Play Group") +
  theme_minimal() +
  scale_x_discrete(limits = play_groups) +
  scale_y_discrete(limits = rev(play_groups))

print(confusion_heatmap_play_group)

# calculate directionally independent accuracy (no left/right)

accuracy_play_group <- mean(predicted_play_group == true_play_group)
cat("Ignoring left and right, the model's accuracy when predicting the play 
    group is", round(accuracy_play_group, 4), "\n")

```



``` {r hyperparameter tuning setup}


# function to perform hyperparameter tuning (i.e. training en mass)
train_and_evaluate <- function(X_train, Y_train, X_test, Y_test, eta, q, epochs, 
                               alpha_relu = 0.01) {

  errors <- numeric(epochs) # track errors over epochs
  set.seed(40) # maintain state
  
  n <- nrow(X_train) # number of samples
  d <- ncol(X_train) # number of features + 1 (bias term)
  k <- ncol(Y_train) # number of classes
  
  W1 <- matrix(rnorm(d * q), nrow = d, ncol = q) # initial W1
  W2 <- matrix(rnorm(q * k), nrow = q, ncol = k) # initial W2
  
  # leaky relu
  leaky_relu <- function(x, alpha = 0.01) {
    ifelse(x > 0, x, alpha * x)
  }
  
  # softmax
  softmax <- function(x) {
    x_shift <- x - apply(x, 1, max) # infinity values were causing errors
    exp_x <- exp(x_shift)
    exp_x / rowSums(exp_x)
  }
  
  # forward pass func
  forward_pass <- function(X, W1, W2) {
    Hidden_input <- X %*% W1              
    Hidden_output <- leaky_relu(Hidden_input)
    Output_input <- Hidden_output %*% W2          
    Y_pred <- softmax(Output_input)       
    
    list(Y_pred = Y_pred, Hidden_output = Hidden_output, 
         Hidden_input = Hidden_input)
  }
  
  # backprop
  for (epoch in 1:epochs) {
    # forward pass
    fwd <- forward_pass(X_train, W1, W2)
    
    # gradients
    dW2 <- t(fwd$Hidden_output) %*% (fwd$Y_pred - Y_train) / n
    dW1 <- t(X_train) %*% (((fwd$Y_pred - Y_train) %*% t(W2)) * 
                             ifelse(fwd$Hidden_input > 0, 1, 0.01)  ) / n
    
    # weight updates
    W2 <- W2 - eta * dW2
    W1 <- W1 - eta * dW1
    
    # calculate and track loss
    epsilon <- 1e-15 # to avoid log(0) error 
    L <- -mean(rowSums(Y_train * log(fwd$Y_pred + epsilon)))
    errors <- c(errors, L)
  }
  
  # evaluate acccuracy on test data
  fwd_test <- forward_pass(X_test, W1, W2)
  predicted <- apply(fwd_test$Y_pred, 1, which.max)
  true <- apply(Y_test, 1, which.max)
  accuracy <- mean(predicted == true)
  
  return(list(accuracy = accuracy, W1 = W1, W2 = W2, errors = errors))
}

```



``` {r hyperparameter tuning}

# hyperparameter ranges
etas <- c(0.1, 0.01, 0.001) # step sizes
qs <- c(6, 12, 24) # hidden nodes
epochs_list <- c(500) # number of epochs - choosing only 500 for efficiency

# track output
results <- data.frame(
  eta = numeric(), 
  q = integer(), 
  epochs = integer(), 
  test_accuracy = numeric()
)

# track outputs
error_lists <- list()
best_accuracy <- 0
best_params <- list()

# run through all possible hyperparameter combinations
run_id <- 1
for (eta in etas) {
  for (q in qs) {
    for (epoch in epochs_list) {
      cat("Step size:", eta, ", Width:", q, ", Epcohs:", epoch)
      
      # train with current combination
      model <- train_and_evaluate(
        X_train = X_train, 
        Y_train = Y_train, 
        X_test = X_test, 
        Y_test = Y_test, 
        eta = eta, 
        q = q, 
        epochs = epoch
      )
      
      # track accuracy and errors
      current_accuracy <- model$accuracy
      results <- rbind(
        results, 
        data.frame(
          run_id = run_id,
          eta = eta, 
          q = q, 
          epochs = epoch, 
          test_accuracy = current_accuracy
        )
      )
      error_lists[[as.character(run_id)]] <- model$errors
      
      # check if best 
      if (current_accuracy > best_accuracy) {
        best_accuracy <- current_accuracy
        best_params <- list(eta = eta, q = q, epochs = epochs, 
                            W1 = model$W1, W2 = model$W2)
      }
      
      cat("Current model accuracy is", round(current_accuracy, 4), "\n")
      run_id <- run_id + 1
    }
  }
}

# output all combinations in descending order of performance
print(results[order(-results$test_accuracy), ])

```


``` {r hyperparameter tuning errors graphs}

# df to plot errors
errors_df <- data.frame()
epochs_count <- epochs_list[1]

# fix data aggregation issue
for (id in results$run_id) {
    errors <- error_lists[[as.character(id)]]
    clean_errors <- errors[501:length(errors)]
    temp <- data.frame(
        epoch = 1:500, 
        loss = clean_errors,
        eta = results$eta[results$run_id == id],
        q = results$q[results$run_id == id]
    )
    errors_df <- rbind(errors_df, temp)
}

# legend label
errors_df$label <- paste0(
  "eta=", errors_df$eta, 
  ", q=", errors_df$q
)

# plot error vs epochs curves
ggplot(errors_df, aes(x = epoch, y = loss, color = label)) +
  geom_line(linewidth = 0.8, position = "identity") +
  labs(
    title = "Hyperparameter Tuning",
    x = "Epoch",
    y = "Loss",
    color = "Hyperparameters (eta, q)"
  ) +
  theme_minimal() +
  scale_color_brewer(palette = "Set1")

```